default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-40403_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-40403_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: furima_40403
  username: furima_40403_user
  password: <%= ENV['G1SClSTTJDmW2tdPgs9a8gxsqAexbIak'] %>
  host: dpg-cper05n109ks73fit2f0-a
  port: 5432